---
- name: create a group file for {{ groupname }}
  copy:
    dest: "../vars/groups/{{ groupname }}.yml"
    content: |
      username: "{{ groupname }}"
      state: "present"

- name: load the group file for {{ groupname }}
  include_vars: "groups/{{ groupname }}.yml"

- name: create a group {{ groupname }}
  group:
    name: "{{ groupname }}"
    state: present
  become: true
