---
- name: update the status of group to absent
  lineinfile:
    path: "../vars/groups/{{ groupname }}.yml"
    line: "state: absent"
    regexp: "^state:.*"

- name: load the group file for {{ groupname }}
  include_vars: "groupname/{{ groupname }}.yml"

- debug: var=groupname
- debug: var=state

- name: delete group {{ groupname }}
  user:
    name: "{{ groupname }}"
    state: absent
  become: true
