---
- name: update the status of group to absent
  lineinfile:
    path: "../vars/groups/{{ groupname }}.yml"
    line: "state: absent"
    regexp: "^state:.*"

- name: load the group file for {{ groupname }}
  include_vars: "groups/{{ groupname }}.yml"

- name: delete group {{ groupname }}
  group:
    name: "{{ groupname }}"
    state: absent
  become: true
