---

- name: setup users from file
  include_tasks: users_setup.yml 
  vars:
    file= "{{ item }}"
  with_fileglob:
    - "vars/users/*"

- name: setup groups from file
  include_tasks: groups_setup.yml
  vars:
    file= "{{ item }}"
  with_fileglob:
    - "vars/groups/*"
