---
- name: load the user file for {{ username }}
  include_vars: "users/{{ username }}.yml"

- name: update the key
  lineinfile:
    path: "../vars/users/{{ username }}.yml"
    line: "pub_key: {{ pub_key }}"
    regexp: "^pub_key:.*" 

- name: add authorized keys for {{ username }}
  authorized_key:
    user: "{{ username }}"
    key: "{{ pub_key }}"
  become: true 
